main: io.github.aleksandarharalanov.stairfix.StairFix
version: 1.1.0
name: StairFix
author: Beezle
website: github.com/AleksandarHaralanov/StairFix
description: Makes broken stairs drop the stair block back instead of a plank or cobble.